#!/bin/bash

get_size() {
    bytes="$(stat -c %s "$1")"
    MiB="$(echo "$bytes * 0.0000009537" | bc -l)"
    echo "$MiB"
}

concat() {
    tmp="/tmp/$(date -u +%Y%m%d%H%M%S)"
    cat "$@" > "$tmp"
    echo "$tmp"
}

get_retention() {
    file_size="$(get_size "$1")"
    max_age=365
    min_age=30
    max_size=512
    echo "$min_age + (- $max_age + $min_age) * (($file_size / $max_size - 1) ^ 3)" | bc -l
}

main() {
    file="$(concat "$@")"

    if link="$(curl -s -F "file=@$file" 0x0.st)"; then
        echo "$link" | xclip -selection clipboard
        printf "Link: %s\nFile will be deleted in %.0f days\n" "$link" "$(get_retention "$file")"
    else
        echo "An error occured. Check your internet connection"
    fi

    rm "$file"
}

if [[ "${#@}" -eq 0 ]]; then
    echo "No file provided"
    exit
fi

main "$@"
