#!/bin/sh

mount_point="$HOME/.local/share/android"

mount(){
    aft-mtp-mount "$mount_point"
    notify-send --icon=~/.config/dunst/android.png "Device mounted"
}

unmount(){
    fusermount -u "$mount_point"
    notify-send --icon=~/.config/dunst/android.png "Device unmounted"
}

while getopts "mu" arg 2>/dev/null; do
    case "${arg}" in
        m) mount ;;
        u) unmount ;;
        *) echo "invalid option" ;;
    esac
done
