#!/bin/sh

bms="$HOME/.local/share/bms"

choose() {
    chosen="$(dmenu -i -l 30 < "$bms")" || exit
    "$BROWSER" "$chosen"
}

insert() {
    url="$(echo | dmenu -i -p "Enter url")"
    [ -z "$url" ] && exit
    echo "$url" >> "$bms"
}

copy() {
    [ -t 0 ] &&
        fzf < "$bms" | xclip -selection clipboard
}

noOpt=1
while getopts "is" arg 2>/dev/null; do
    case "${arg}" in
        i) insert ;;
        s) choose ;;
        *) echo "invalid option" ;;
    esac
    noOpt=0
done
[ "$noOpt" -eq 1 ] && copy
