#!/bin/sh

path="/sys/class/backlight/amdgpu_bl0/brightness"
initial="$(cat $path)"
max_brightness="$(cat /sys/class/backlight/amdgpu_bl0/max_brightness)"

case "$1" in
    inc) delta="$((initial+5))" ;;
    dec) delta="$((initial+(-5)))" ;;
    bigInc) delta="$((initial+30))" ;;
    bigDec) delta="$((initial+(-30)))" ;;
esac >/dev/null

if [ "$delta" -lt 0 ]
then
    echo 0 > $path
elif [ "$delta" -gt "$max_brightness" ]
then
    echo "$max_brightness" > $path
else
    echo "$delta" > $path
fi

pkill -RTMIN+14 lemonaid
