#!/bin/sh

info="$HOME/.cache/corona-info"

[ "$(stat -c %y "$info" 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
    if [ "$(ci)" -eq 1 ]; then
        curl -Lso "$info" "https://corona-stats.online"
    else
        echo "You are not connected to the internet. Fetching cached info.."
    fi

if [ -n "$1" ]; then
    exec head -"$1" "$info"
    exit
fi

exec less < "$info"
