#!/bin/sh

app="$*"
heroku create "$app"

[ "$?" -ne 0 ] && exit 1
heroku stack:set container

[ "$?" -ne 0 ] && exit 1
echo 'build:
    docker:
        web: Dockerfile
run:
    web: ./main' > heroku.yml

[ "$?" -ne 0 ] && exit 1
git remote add heroku "https://git.heroku.com/${app}.git"
