#!/bin/sh

if [ -z "$1" ]; then
    echo "Please provide a url"
    exit 1
fi

name="$(date -u +%Y%m%d%H%M%S)"
yt-dlp -o "${name}_tmp.%(ext)s" --merge-output-format mp4 "$1"
ffmpeg -y -f mpegts -i "${name}_tmp.mp4" -c copy "${name}.mp4"

# clean up
rm "${name}_tmp.mp4"
