#!/bin/sh

[ -z "$1" ] && exit 1

if command -v devour >/dev/null; then
    case "$1" in
        *.jpg|*.jpeg|*.png) exec devour sxiv "$1" ;;
        *.mp4|*.mkv|*.wav|*.mp3) exec devour mpv "$1" ;;
        *.pdf|*.epub) exec devour zathura "$1" ;;
        *.docx|*.doc|*.pptx|*.ppt|*.odt) exec devour zaread "$1" ;;
        *) exec nvim "$1" ;;
    esac

    exit 0
fi

case "$1" in
    *.jpg|*.jpeg|*.png) exec sxiv "$1" ;;
    *.mp4|*.mkv|*.wav|*.mp3) exec mpv "$1" ;;
    *.pdf|*.epub) exec zathura "$1" ;;
    *.docx|*.doc|*.pptx|*.ppt|*.odt) exec zaread "$1" ;;
    *) exec nvim "$1" ;;
esac
