#!/bin/bash

readarray -d '' files < <(find "$HOME/" -name "*.pdf" -print0)

if [[ -n "$COMP_LINE" ]]; then
    for f in "${files[@]}"; do
        f="${f##*/}"
        [[ "${f:0:${#2}}" == "${2,,}" ]] && echo "$f"
    done
    exit 0
fi

if [[ -z "$1" ]]; then
    for f in "${files[@]}"; do
        f="${f##*/}"
        echo "$f"
    done
    exit 0
fi

for f in "${files[@]}"; do
    if [[ "${f##*/}" = "$1" ]]; then
        path="$f"
        break
    fi
done

if [[ -z "$path" ]]; then
    echo "no such pdf exists"
    exit 1
fi

exec o "$path"
