#!/bin/sh

if [ -z "$1" ]; then
    pacman -Slq |
        fzf --multi --preview 'pacman -Si {1}' |
        xargs -I {} sudo pacman --noconfirm --needed -S {}

    exit
fi

pacman -Sgg |
    grep blackarch |
    cut -d' ' -f2 |
    sort -u |
    fzf --multi --preview 'pacman -Si {1}' |
    xargs -I {} sudo pacman --noconfirm --needed -S {}
