#!/bin/sh

location="$HOME/Pictures/wallpapers/" # location of your wallpapers directory
cache="$HOME/.cache/wall" # location of cache file

help(){
    printf "## Usage
run sbg without any argument to select a wallpaper from %s\n
sbg [optional arguments]
-h\tDisplays this help menu
-d\tdraws the wallpaper at startx. Add 'sbg -d' in your xinitrc
-r\trandomly selects a wallpaper
-i\tGo insane
" "$location"
}

change(){
    echo "$1" > "$cache"
    xwallpaper --stretch "$1" 2>/dev/null
}

shuffle(){
    find "$location" | shuf -n 1
}

random(){
    change "$(shuffle)"
}

goInsane(){
    while true; do
        change "$(shuffle)"
        sleep 1s
    done
}

menu(){
    input=$(printf "set background\nrandom\ngo insane" | dmenu -i) || exit
    case "$input" in
        "set background") change "$(sxiv -b -t -o "$location")" ;;
        "random") random ;;
        "go insane") goInsane ;;
    esac
}

setbg(){
    if [ -z "$1" ]; then
        menu
        exit
    fi

    change "$1"
}

draw(){
    last_drawn="$(cat "$cache" 2>/dev/null)"

    # if cache file is deleted, draw a random wallpaper
    if [ -z "$last_drawn" ]; then
        random
        exit
    fi

    change "$last_drawn"
}

noOpt=1
while getopts "hdrim" arg 2>/dev/null; do
    case "${arg}" in
        h) help ;;
        d) draw ;;
        r) random ;;
        i) goInsane ;;
        *) printf "invalid option.\nsbg -h for help" ;;
    esac
    noOpt=0
done
[ "$noOpt" -eq "1" ] && setbg "$1"
