#!/bin/sh

chosen="$(find "$HOME"/.local/scripts/ -maxdepth 1 -type f |
    sed 's/\/home\/murtaza\/.local\/scripts\///g' |
    fzf -i --border sharp)"

[ -z "$chosen" ] || nvim "$HOME/.local/scripts/$chosen"
