#!/bin/sh

notify() {
    notify-send --icon=~/.config/dunst/screenshot.png "Screenshot taken"
}

choice="$(printf 'Fullscreen\nFocused window\nInteractive' | dmenu -i -l 20 -p 'screenshot ')"

case "$choice" in
    'Fullscreen') scrot -d 0.6 '/home/murtaza/Pictures/screenshots/%Y-%m-%d-@%H-%M-%S.png' && notify ;;
    'Focused window') scrot -u '/home/murtaza/Pictures/screenshots/%Y-%m-%d-@%H-%M-%S.png' && notify ;;
    'Interactive') scrot -s '/home/murtaza/Pictures/screenshots/%Y-%m-%d-@%H-%M-%S.png' && notify ;;
esac
