#!/bin/bash

# This script is horribly written. I know okay

ALACRITTY="$HOME/.config/alacritty/alacritty.yml"
NVIM="$HOME/.config/nvim/init.vim"
TMUX="$HOME/.tmux.conf"
DARK_THEME="gruvbox_dark"
LIGHT_THEME="gruvbox_light"

DARK_TMUX='set -g pane-border-style "fg=#161515,bg=#161515"\nset -g pane-active-border-style "fg=#161515,bg=#161515"\nset -g status-style "bg=#161515,fg=#f2e5bc"'
LIGHT_TMUX='set -g status-style "bg=#f2e5bc,fg=#665c54"\nset -g pane-border-style "fg=#f2e5bc,bg=#f2e5bc"\nset -g pane-active-border-style "fg=#f2e5bc,bg=#f2e5bc"'

transparent_bg() {
    BG1="#000000"
    BG2="#161515"

    target="$(grep -n -m 1 -A 2 "$DARK_THEME" "$ALACRITTY" | tail -n 1)"
    current_bg="$(echo "$target" | cut -d"'" -f2)"
    line_num="$(echo "$target" | cut -d'-' -f1)"

    if [ "$current_bg" = "$BG1" ]
    then
        sed -i "${line_num}s/$BG1/$BG2/" "$ALACRITTY"
        opacity -s 1.0
    else
        sed -i "${line_num}s/$BG2/$BG1/" "$ALACRITTY"
        opacity -s 0.9
    fi
}

change_theme() {
    target="$(grep -n colors "$ALACRITTY" | tail -n 1)"
    current_theme="$(echo "$target" | cut -d'*' -f2)"
    line_num="$(echo "$target" | cut -d':' -f1)"

    colors_num="$(grep -n colors "$TMUX" | cut -d':' -f1)"
    sed -i "$((colors_num + 1)),\$d" "$TMUX"

    if [ "$current_theme" = "$DARK_THEME" ]; then
        sed -i "${line_num}s/$DARK_THEME/$LIGHT_THEME/" "$ALACRITTY"
        sed -i "s/set background=dark/set background=light/" "$NVIM"
        sed -i "/^# colors/a $LIGHT_TMUX" "$TMUX"
    else
        sed -i "${line_num}s/$LIGHT_THEME/$DARK_THEME/" "$ALACRITTY"
        sed -i "s/set background=light/set background=dark/" "$NVIM"
        sed -i "/^# colors/a $DARK_TMUX" "$TMUX"
    fi

    tmux source-file ~/.tmux.conf
}

while getopts "bt" arg 2>/dev/null; do
    case "${arg}" in
        b) transparent_bg ;;
        t) change_theme ;;
        *) echo "invalid option" ;;
    esac
done
