#!/usr/bin/env bash

username="murtaza"

function update() {
  nix flake update
}

function switch-nixos() {
  sudo nixos-rebuild switch --flake .#
}

function switch-home-manager() {
  nix run .#homeManagerConfigurations.$username.activationPackage
}

######## bash completion context ########

root=(update switch)
switch=(nixos home-manager)

comp() {
    local arg="$1"
    shift

    for c in "$@"; do
        [[ "${c:0:${#arg}}" == "${arg,,}" ]] && echo "$c"
    done
}

if [[ -n "$COMP_LINE" ]]; then
    if [[ "$1" == "$3" ]]; then
        comp "$2" "${root[@]}"
        exit 0
    fi

    comp "$2" "${switch[@]}"
    exit 0
fi

numargs="${#@}"

if [[ "$numargs" -lt 1 ]]; then
    echo "very few arguments"
    exit 1
fi

cmd="$1"
arg="$2"

case "$cmd" in
  "update")
    update
    ;;
  "switch")
    case "$arg" in
      nixos) switch-nixos ;;
      home-manager) switch-home-manager ;;
      "") switch-nixos && switch-home-manager ;;
      *) echo "invalid command" ;;
    esac
    ;;
  *) echo "invalid command" ;;
esac
