#!/bin/sh

img="$1"

if [ "$img" = "grafana" ]; then
    docker run --name=grafana -p 3000:3000  --network host grafana/grafana:11.6.0
fi

if [ "$img" = "postgres" ]; then
    echo "POSTGRES_USER: postgres"
    echo "POSTGRES_PASSWORD: postgres"
    echo "POSTGRES_DB: postgres"

    data="$HOME/.local/share/postgres"
    mkdir "$data" -p

    exec docker run -d \
        --rm \
        --name postgres \
        --hostname postgres \
        --env POSTGRES_USER=postgres \
        --env POSTGRES_PASSWORD=postgres \
        --env PGDATA=/var/lib/postgresql/data/pgdata \
        --volume="$data:/var/lib/postgresql/data:Z" \
        -p 5432:5432 \
        postgres:17.2-alpine3.21
    exit 0
fi

if [ "$img" = "mysql" ]; then
    echo "MYSQL_ROOT_PASSWORD: toor"

    data="$HOME/.local/share/mysql"
    mkdir "$data" -p

    exec docker run -d \
        --rm \
        --name mysql \
        --hostname mysql \
        --env MYSQL_ROOT_PASSWORD=toor \
        --volume="$data:/var/lib/mysql:Z" \
        -p 3306:3306 \
        mysql:8.3.0
    exit 0
fi

if [ "$img" = "mariadb" ]; then
    echo "MARIADB_ROOT_PASSWORD: toor"

    data="$HOME/.local/share/mariadb"
    mkdir "$data" -p

    exec docker run -d \
        --rm \
        --name mariadb \
        --hostname mariadb \
        --env MARIADB_ROOT_PASSWORD=toor \
        --volume="$data:/var/lib/mysql:Z" \
        -p 3306:3306 \
        mariadb:lts
    exit 0
fi

if [ "$img" = "keye" ]; then
    data="$HOME/.local/share/keye"
    mkdir "$data" -p

    exec docker run -it -d \
        --name keye \
        -p 23023:23023 \
        -v "$data:/data" \
        -e "KEYE_DB_FILE_PATH=/data/data.db" \
        -e "KEYE_PORT=23023" \
        -e "KEYE_WATCHER_PING_INTERVAL=10s" \
        -e "KEYE_EVENT_QUEUE_SIZE=10" \
        -e "KEYE_ENABLE_REFLECTION=0" \
        -e "KEYE_USE_JSON_LOGGER=0" \
        -e "KEYE_DEBUG=1" \
        murtazau/keye:23.12
    exit 0
fi

if [ "$img" = "mongo" ]; then
    echo "MONGO_INITDB_ROOT_PASSWORD: toor"

    data="$HOME/.local/share/mongodb"
    mkdir "$data" -p

    exec docker run -d \
        --rm \
        --name mongo \
        --hostname mongo \
        --env MONGO_INITDB_ROOT_USERNAME=root \
        --env MONGO_INITDB_ROOT_PASSWORD=toor \
        --volume="$data:/data/db" \
        -p 27017:27017 \
        mongo:8.0.1-noble
    exit 0
fi

if [ "$img" = "etcd" ]; then
    node="127.0.0.1"
    data="$HOME/.local/share/etcd"
    mkdir "$data" -p

    docker run -it -d \
        -p 2379:2379 \
        -p 2380:2380 \
        --restart=always \
        --mount "type=bind,source=$data,destination=/var/run/etcd" \
        --name etcd \
        --hostname etcd \
        quay.io/coreos/etcd:v3.5.13 \
        /usr/local/bin/etcd \
        --name etcd \
        --listen-peer-urls http://0.0.0.0:2380 \
        --listen-client-urls http://0.0.0.0:2379 \
        --advertise-client-urls "http://$node:2379" \
        --initial-advertise-peer-urls "http://$node:2380" \
        --initial-cluster-token etcd-cluster-1 \
        --initial-cluster "etcd=http://$node:2380" \
        --initial-cluster-state new \
        --data-dir /var/run/etcd
    exit 0
fi

exec docker run -it --name "$1" --hostname "$1" --rm "$1"
