#!/usr/bin/env bash

if [[ -n "$BASH_VERSION" && -f "$HOME/.bashrc" ]]; then
    # source .bashrc if it exists
    . "$HOME/.bashrc"
fi

# ----------------------------- exports ---------------------------------------
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="$HOME/.local/share/runtime"

export TERMINAL=xfce4-terminal
export BROWSER=chromium
export READER=zathura
export COLORTERM=truecolor
export CGO_ENABLED=0
export REPOS="$HOME/Repos"
export GITUSER=murtaza-u

# go
export GOPATH="$XDG_DATA_HOME/go"
export GOBIN="$GOPATH/bin"

# npm
export prefix="$XDG_DATA_HOME/npm"
export cache="$XDG_CACHE_HOME/npm"
export tmp="$XDG_RUNTIME_DIR/npm"
export NPM_CONFIG_PREFIX="$HOME/.local/share/npm-global"

# clean up
export LESSHISTFILE="-"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

# fixes
export MOZ_USE_XINPUT2=1  # Mozilla smooth scrolling/touchpads.
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
