#!/bin/sh

userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f "$sysresources" ] && xrdb -merge "$sysresources"

[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"

[ -f "$userresources" ] && xrdb -merge "$userresources"

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap" && xmodmap -e "clear lock"
fi

sxhkd &
exec startxfce4
