#!/usr/bin/env bash

while read -r file; do
    case "$1" in
        "r") convert -rotate 90 "$file" "$file" ;;
        "R") convert -rotate -90 "$file" "$file" ;;
        "f") convert -flop "$file" "$file" ;;
        "d") rm -f "$file" ;;
        "y") xclip -sel c <<< "$file" ;;
        "Y") xclip -sel c <<< $(readlink -f "$file") ;;
    esac
done
