#!/usr/bin/env bash

if [[ -z "$(command -v brightnessctl)" ]]; then
    echo "brightnessctl not installed"
    exit 1
fi

u="$(brightnessctl get)"
v=0
MAX_BRIGHTNESS="$(</sys/class/backlight/amdgpu_bl0/max_brightness)"

inc() {
    d="$1"
    [[ -z "$d" ]] && d=5

    v="$((u+d))"
    if [[ "$v" -ge "$MAX_BRIGHTNESS" ]]; then
        brightnessctl set "$MAX_BRIGHTNESS"
        return
    fi

    brightnessctl set "$v"
}

dec() {
    d="$1"
    [[ -z "$d" ]] && d=5

    v="$((u-d))"
    if [[ "$v" -le 0 ]]; then
        brightnessctl set 0
        return
    fi

    brightnessctl set "$v"
}

case "$1" in
    inc) inc "$2" ;;
    dec) dec "$2" ;;
    *) exit 1 ;;
esac >/dev/null

exec dunstify -i "$HOME/.config/dunst/brightness.png" "$v"
