#!/usr/bin/env bash

hidecursor() {
    if type setterm >/dev/null 2>&1; then
        exec setterm --cursor off
    fi
}

showcursor() {
    if type setterm >/dev/null 2>&1; then
        exec setterm --cursor on
    fi
}

comp() {
    cmds=(hide show)
    for c in "${cmds[@]}"; do
        [[ "${c:0:${#2}}" == "${2,,}" ]] && echo "$c"
    done
}
if [[ -n "$COMP_LINE" ]]; then
    comp "$@"
    exit 0
fi

case "$1" in
    "show") showcursor ;;
    "hide") hidecursor ;;
esac
