#!/usr/bin/env bash

pre() {
    accounts=("college" "personal" "admybrand")
    for account in "${accounts[@]}"; do
        mkdir -p "$HOME/.cache/mutt/accounts/$account/headers"
        mkdir -p "$HOME/.cache/mutt/accounts/$account/bodies"
    done
    chmod 700 "$HOME/.cache/mutt/accounts"
}

pre

declare -a accounts
dir="$HOME/.config/mutt/"

mapfile -t accounts < <(find "$dir" -name "account.*")

for (( i=0; i<${#accounts[@]}; i++ )); do
    accounts[i]="${accounts[i]##*/}"
    accounts[i]="${accounts[i]//account./}"
done

comp() {
    for a in "${accounts[@]}"; do
        [[ "${a:0:${#2}}" == "${2,,}" ]] && echo "$a"
    done
}

if [[ -n "$COMP_LINE" ]]; then
    comp "$@"
    exit 0
fi

arg="$1"
if [[ -z "$arg" ]]; then
    select account in "${accounts[@]}"; do
        arg="$account"
        break
    done
fi

exec neomutt -F "${dir}account.${arg}"
