#!/usr/bin/env bash

if [[ ! -x /usr/bin/figlet ]]; then
    echo "figlet not installed"
    exit 1
fi

if [[ ! -x /usr/games/lolcat ]]; then
    echo "lolcat not installed"
    exit 1
fi

clear=$'\033[2J'
top=$'\033[H'

trap 'setterm --cursor on; stty echo; echo ${clear}; exit; trap -- - SIGINT SIGTERM' SIGTERM SIGINT

echo "${clear}"
while true; do
    echo "${top}"
    stty -echo
    setterm --cursor off
    figlet -f future.tlf -c -t "$*" | lolcat 2>/dev/null
    setterm --cursor off
    sleep 3
done
