#!/bin/sh

lynxpath=/usr/bin/lynx
lss="$HOME/.config/lynx/lynx.lss"
cfg="$HOME/.config/lynx/lynx.cfg"
useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.79 Safari/537.1 Lynx"

if [ ! -x "$lynxpath" ]; then
    echo "lynx is likely not installed"
    exit 1
fi


[ -e "$cfg" ] && export LYNX_CFG="$cfg"
[ -e "$lss" ] && export LYNX_LSS="$lss"

exec "$lynxpath" --useragent="$useragent" "$@"
