#!/bin/sh

# exec xdg-open "$@"

[ -z "$*" ] && exit 1

pre="exec"
command -v devour >/dev/null && pre="exec devour"

case "$1" in
    *.jpg|*.jpeg|*.png) $pre sxiv "$@" ;;
    *.mp4|*.mkv|*.wav|*.mp3) $pre mpv "$@" ;;
    *.pdf|*.epub) $pre zathura "$@" ;;
    *.docx|*.doc|*.pptx|*.ppt|*.odt) $pre zaread "$@" ;;
    *) exec nvim "$@" ;;
esac
