#!/usr/bin/env bash

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}

password_files=( "$prefix"/**/otp/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

selected="$(printf '%s\n' "${password_files[@]}" | dmenu -i)"
[[ -z "$selected" ]] && exit

exec pass otp -c "$selected"
