#!/bin/sh

if [ -z "$(command -v zbarimg)" ]; then
    echo "zbarimg is not installed"
    exit 1
fi

img="$1"
if [ ! -f "$img" ]; then
    echo "file $img does not exist"
    exit 1
fi

zbarimg "$img"
