#!/bin/sh

INRES="1920x1080"
OUTRES="1920x1080"
FPS="60"

exec ffmpeg -f x11grab -s "$INRES" -r "$FPS" -i :0.0 -f pulse -ac 2 \
    -i default -vcodec libx264 -s "$OUTRES" \
    -acodec libmp3lame -ab 128k -ar 44100 \
    -threads 0 "$1"
