#!/bin/sh

img="$1"

if [ "$img" = "mysql" ]; then
    echo "MYSQL_ROOT_PASSWORD: toor"

    exec docker run -d \
        --rm \
        --name mysql \
        --hostname mysql \
        --env MYSQL_ROOT_PASSWORD=toor \
        --volume="$HOME"/.local/share/mysql:/var/lib/mysql \
        -p 3306:3306 \
        mysql
    exit 0
fi

if [ "$img" = "mongo" ]; then
    echo "MONGO_INITDB_ROOT_PASSWORD: toor"

    exec docker run -d \
        --rm \
        --name mongo \
        --hostname mongo \
        --env MONGO_INITDB_ROOT_USERNAME=root \
        --env MONGO_INITDB_ROOT_PASSWORD=toor \
        --volume="$HOME"/.local/share/mongodb:/data/db \
        -p 27017:27017 \
        mongo:4.4.19-rc0-focal

    exit 0
fi

if [ "$img" = "etcd" ]; then
    NODE="127.0.0.1"
    VOL="$HOME/.local/share/etcd"
    mkdir -p "$VOL"

    docker run -it -d \
        -p 2379:2379 \
        -p 2380:2380 \
        --mount type=bind,source="$VOL",destination=/var/run/etcd \
        --name etcd \
        --hostname etcd \
        quay.io/coreos/etcd:v3.5.7 \
        /usr/local/bin/etcd \
        --name etcd \
        --listen-peer-urls http://0.0.0.0:2380 \
        --listen-client-urls http://0.0.0.0:2379 \
        --advertise-client-urls http://${NODE}:2379 \
        --initial-advertise-peer-urls http://${NODE}:2380 \
        --initial-cluster-token etcd-cluster-1 \
        --initial-cluster etcd=http://${NODE}:2380 \
        --initial-cluster-state new \
        --data-dir /var/run/etcd
    exit 0
fi

exec docker run -it --name "$1" --hostname "$1" --rm "$1"
