#!/usr/bin/env bash

accounts=("college" "personal" "admybrand")

for account in "${accounts[@]}"; do
    mkdir -p "$HOME/.cache/mutt/accounts/$account/headers"
    mkdir -p "$HOME/.cache/mutt/accounts/$account/bodies"
done

chmod 700 "$HOME/.cache/mutt/accounts"
