#!/usr/bin/env bash

device="ELAN1301:00 04F3:30C6 Touchpad"

is_disabled() {
    [[ "$(xinput --list "$device")" =~ disabled ]]

    if [[ -z "${BASH_REMATCH[0]}" ]]; then
        echo false
        return
    fi

    echo true
}

notify() {
    notify-send -i "$2" "$1"
}

if [[ "$(is_disabled)" == "true" ]]; then
    xinput enable "$device"
    notify "Touchpad Enabled" "$HOME/.config/dunst/touchpad_enabled.png"
    exit
fi

xinput disable "$device"
notify "Touchpad Disabled" "$HOME/.config/dunst/touchpad_disabled.png"
