#!/usr/bin/env bash

device="ELAN1301:00 04F3:30C6 Touchpad"

is_disabled() {
    [[ "$(xinput --list "$device")" =~ disabled ]]

    if [[ -z "${BASH_REMATCH[0]}" ]]; then
        echo false
        return
    fi

    echo true
}

if [[ "$(is_disabled)" == "true" ]]; then
    xinput enable "$device"
    exit
fi

xinput disable "$device"
