#!/usr/bin/env bash

readarray -d '' files < <(find "$HOME/.local/scripts/" -type f -print0)

if [[ -n "$COMP_LINE" ]]; then
    for f in "${files[@]}"; do
        f="${f##*/}"
        [[ "${f:0:${#2}}" == "${2,,}" ]] && echo "$f"
    done
    exit 0
fi

path="$(command -v "$*")"
if [[ -z "$path" ]]; then
    echo "not found"
    exit 1
fi

exec "$EDITOR" "$path"
