#!/bin/sh

notify() {
    icon="$1"
    body="$2"
    notify-send -i "$icon" "$body"
}

is_out_mute() {
    pamixer --get-mute
}

is_in_mute() {
    pamixer --source 1 --get-mute
}

get_out_vol() {
    pamixer --get-volume
}

get_in_vol() {
    pamixer --source 1 --get-volume
}

inc_out() {
    d="$1"
    [ -z "$d" ] && d=5
    pamixer --allow-boost -i "$d"
}

inc_in() {
    d="$1"
    [ -z "$d" ] && d=5
    pamixer --allow-boost --source 1 -i "$d"
}

dec_out() {
    d="$1"
    [ -z "$d" ] && d=5
    pamixer --allow-boost -d "$d"
}

dec_in() {
    d="$1"
    [ -z "$d" ] && d=5
    pamixer --allow-boost --source 1 -d "$d"
}

up_cmd() {
    if [ "$(is_out_mute)" = "true" ]; then
        notify "$HOME/.config/dunst/speaker_mute.png" "mute"
        exit 0
    fi

    inc_out "$1"
    vol="$(get_out_vol)"
    notify "$HOME/.config/dunst/speaker.png" "$vol"
}

down_cmd() {
    if [ "$(is_out_mute)" = "true" ]; then
        notify "$HOME/.config/dunst/speaker_mute.png" "mute"
        exit 0
    fi

    dec_out "$1"
    vol="$(get_out_vol)"
    notify "$HOME/.config/dunst/speaker.png" "$vol"
}

toggle_output_cmd() {
    pamixer -t

    if [ "$(is_out_mute)" = "true" ]; then
        notify "$HOME/.config/dunst/speaker_mute.png" "mute"
        exit 0
    fi

    vol="$(get_out_vol)"
    notify "$HOME/.config/dunst/speaker.png" "$vol"
}

toggle_input_cmd() {
    pamixer --source 1 -t

    if [ "$(is_in_mute)" = "true" ]; then
        notify "$HOME/.config/dunst/mic_mute.png" "mute"
        exit 0
    fi

    vol="$(get_in_vol)"
    notify "$HOME/.config/dunst/mic.png" "$vol"
}

if [ ! "$(command -v pamixer)" ]; then
    echo "pamixer not installed"
    exit 1
fi

if [ -z "$1" ]; then
    echo "no arguments provided"
    exit 1
fi

case "$1" in
    up) up_cmd "$2" ;;
    down) down_cmd "$2" ;;
    toggle-output) toggle_output_cmd ;;
    toggle-input) toggle_input_cmd ;;
    *) echo "invalid arguments" ;;
esac
