#!/usr/bin/env bash

wall="$HOME/Pictures/wallpapers" # wallpapers directory
cache="$HOME/.cache/wall.db" # cache file
cmds=(set restore random gui)

set() {
    f="$1"
    if [[ ! -r "$f" ]]; then
        echo "error: $f: file not found"
        return 1
    fi

    echo "$f" > "$cache"
    exec xwallpaper --stretch "$f"
}

random() {
    f="$(find "$wall" -type f | shuf -n 1)"
    echo "$f" > "$cache"
    exec xwallpaper --stretch "$f"
}

restore() {
    if [[ ! -r "$cache" ]]; then
        random
        return
    fi

    IFS= read -r f < "$cache"
    if [[ ! -r "$f" ]]; then
        echo "error: $f: file not found"
        return 1
    fi

    exec xwallpaper --stretch "$f"
}

gui() {
    f="$(sxiv -bto "$wall")"
    [[ -z "$f" ]] && return 0

    set "$f"
}

comp() {
    [[ "$1" != "$3" ]] && return

    for cmd in "${cmds[@]}"; do
        cmd="${cmd##*/}"
        [[ "${cmd:0:${#2}}" == "${2,,}" ]] && echo "$cmd"
    done
}

if [[ -n "$COMP_LINE" ]]; then
    comp "$@"
    exit 0
fi

cmd="$1"
if [[ -z "$cmd" ]]; then
    gui
    exit
fi

case "$cmd" in
    set)     set "$1" ;;
    restore) restore ;;
    random)  random ;;
    gui)     gui ;;
    *)       echo "error: $cmd: invalid command" && exit 1 ;;
esac
