#!/usr/bin/env bash

set -e

on() {
    nmcli radio wifi on
    notify-send -i ~/.config/dunst/online.png "Online"
}

off() {
    nmcli radio wifi off
    notify-send -i ~/.config/dunst/offline.png "Offline"
}

cmds=(on off)

if [[ -n "$COMP_LINE" ]]; then
    for c in "${cmds[@]}"; do
        [[ "${c:0:${#2}}" == "${2,,}" ]] && echo "$c"
    done

    exit 0
fi

case "$1" in
    on)  on ;;
    off) off ;;
    *)   echo "invalid arguments" ;;
esac
