#!/bin/sh

exist="$(command -v "xhost")"
if [ -z "$exist" ]; then
    echo "xhost not installed"
    exit 1
fi

xhost +

exec docker run \
    -it \
    --name "$1" \
    --hostname "$1" \
    --rm \
    -e DISPLAY="$DISPLAY" \
    -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
    "$1"
