#!/bin/sh

while read file
do
    case "$1" in
        "d") rm "$file" ;;

        "w") xwallpaper --stretch "$file" ;;

        "r") convert -rotate 90 "$file" "$file" ;;

        "R") convert -rotate -90 "$file" "$file" ;;

        "f") convert -flop "$file" "$file" ;;

        "s") decode "$file" ;;

        "y") echo -n "$file" | tr -d '\n' | xclip -selection clipboard && notify-send "$file copied to clipboard" & ;;
    esac
done
