# dark
# set -g pane-border-style "fg=#171717,bg=#171717"
# set -g pane-active-border-style "fg=#171717,bg=#171717"
# set -g status-style "bg=#171717,fg=#f2e5bc"

# light
# set -g status-style "bg=#f2e5bc,fg=#665c54"
# set -g pane-border-style "fg=#f2e5bc,bg=#f2e5bc"
# set -g pane-active-border-style "fg=#f2e5bc,bg=#f2e5bc"

# change prefix key to C-s
unbind-key C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# window splitting
bind-key | split-window -h
bind-key _ split-window -v
unbind '"'
unbind %

# cycle b/w panes
bind -n M-j select-pane -t :.+
bind -n M-k select-pane -t :.-

# vi keys to resize
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1

# vi keys to navigate panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind-key X kill-window

# reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

# start numbering from 1
set -g base-index 1
set -g pane-base-index 1

# automatically renumber windows
set -g renumber-windows on

# set escape time to 0
set -s escape-time 0

# enable mouse scrolling
set -g mouse on

# avoid cursor movement messing with resize
set -g repeat-time 200

# vi
set -g status-keys vi
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# status bar
set -g status-interval 1
set -g status-right "#(pom)"
set -g status-left-length 60
set -g status-justify centre

# fixes
set -ga terminal-overrides ",alacritty:RGB"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'

# underscore colours
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# colors
set -g pane-border-style "fg=#171717,bg=#171717"
set -g pane-active-border-style "fg=#171717,bg=#171717"
set -g status-style "bg=#171717,fg=#f2e5bc"
