#!/bin/sh

bspc monitor eDP -d 1 2 3 4 5 6 7 8 9

bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.5
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config gapless_monocle true

# colors
bspc config focused_border_color "#000000"
bspc config normal_border_color "#ffffff"
bspc config active_border_color "#8be9fd"
bspc config presel_feedback_color "#50fa7b"

sxhkd &
xwallpaper --stretch /home/murtaza/Pictures/wallpapers/wallhaven-96lzdd.png
xset r rate 250 50
systemctl --user start dunst.service
systemctl --user import-environment DISPLAY
